name: condor-cnn-trans

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10

  # GPU
  - cudatoolkit=11.2
  - cudnn=8.1

  # Scientific stack
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy
  - scikit-learn=1.5.2
  - pyarrow=14.0.2

  - pip

  - pip:
      - tensorflow==2.10.0
      - keras-tuner==1.4.7
      - shap==0.46.0
      - mlflow==2.8.1
      - protobuf==3.19.6
      - setuptools<70.0.0
      - matplotlib==3.9.2
      - seaborn==0.13.2
      - gdown
      - tqdm
      - ipywidgets
      - jupyter
      - notebook
      - papermill
